### ISSUE TITLE
making pages for buildings

### ISSUE THREAD

**Issue by jamesacris** [Jo-stfc/Public-engagement-app#16]

**Comment by Scott-James-Hurley** [comment]
Pages still to be done:

- [ ] R87 - Ridgeway House,  link to website
- [ ] R116 - SCD, make SCD page and link to it
- [ ] R34 - 
- [ ] R56 - Logistics could get rid off
- [ ] R79 - Diamond_BID_ISIS
- [ ] R12 - Technology
- [ ] R76 - 
- [ ] R63 - Technology
- [ ] R65 - Technology
- [ ] R66 - Technology
- [ ] R52 - 
- [ ] R68 - Estates-Technology-RAL space, don't link to estates just put it in the name
- [ ] R104 - BID
- [ ] R25 - Technology-RAL space
- [ ] R1 - HR-Legal-CLF-Technology-Finance-PPD-BID: only use Technology, PPD, BID, don't link to hr, legal, finance just put them in the name
- [ ] R8 - ISIS
- [ ] R9 - Technology
- [ ] R10 - Estates don't link
- [ ] R11 - RFI
- [ ] R79 - Diamond-BID-ISIS
- [ ] R56 - Logistics could get rid of
- [ ] R75 - Reception doesn't need page
- [ ] R92 - Harwell Research Council
- [ ] I14 - 
- [ ] R98/I13 - 

Please put your name next to any pages you are doing.
